### ISSUE TITLE
Pad pri zmene audio stopy

### ISSUE THREAD

**Issue by vatlach** [mx3L/mediaplayer2#8]
VTI 11.0.2 pri vybere audia sposobi pad E2.V klasickom MP je to ok.

**Comment by vatlach** [comment]
[Speech2Text] add callback function
Traceback (most recent call last):
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/MediaPlayer2/plugin.py", line 330, in audioSelection
    self.session.openWithCallback(self.audioSelected, MyAudioSelection, infobar=self)
  File "/usr/lib/enigma2/python/mytest.py", line 336, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 346, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 281, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 312, in doInstantiateDialog
    dlg.applySkin()
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Components/GUISkin.py", line 112, in applySkin
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Components/GUISkin.py", line 47, in createGUIScreen
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Screens/AudioSelection.py", line 75, in __layoutFinished
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Components/config.py", line 130, in addNotifier
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Screens/AudioSelection.py", line 137, in fillList
  File "/media/build01/vti-dorie/build/tmp/work/armv7ahf-vfp-neon-oe-linux-gnueabi/enigma2-python/enigma2-python-vti-13.0.2-20171220-r0r0/git/lib/python/Screens/AudioSelection.py", line 249, in subtitlesEnabled
AttributeError: 'MediaPlayer' object has no attribute 'subtitles_enabled'
(PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x86bc4cd8>>,('InfobarAudioSelectionActions', 'audioSelection')) failed)
]]>
		</dvbapp2crashlog>
	</crashlogs>
</stbcrashlog>

**Comment by vatlach** [comment]
to iste v VTI 13.0.2

**Comment by vatlach** [comment]
Problem vo vti
